#ifndef _AWS_IOT_CONFIG_H_
#define _AWS_IOT_CONFIG_H_

#include "sdkconfig.h"

// Threading support
#define _ENABLE_THREAD_SUPPORT_

// MQTT settings
#define AWS_IOT_MQTT_HOST              "a228r7uur1pofl-ats.iot.us-east-2.amazonaws.com"
#define AWS_IOT_MQTT_PORT              8883
#define AWS_IOT_MQTT_CLIENT_ID         "ESP32"
#define AWS_IOT_MY_THING_NAME          "ESP32"

// MQTT Buffers
#define AWS_IOT_MQTT_TX_BUF_LEN 512
#define AWS_IOT_MQTT_RX_BUF_LEN 512
#define AWS_IOT_MQTT_NUM_SUBSCRIBE_HANDLERS 5

// Shadow configs
#ifdef CONFIG_AWS_IOT_OVERRIDE_THING_SHADOW_RX_BUFFER
#define SHADOW_MAX_SIZE_OF_RX_BUFFER CONFIG_AWS_IOT_SHADOW_MAX_SIZE_OF_RX_BUFFER
#else
#define SHADOW_MAX_SIZE_OF_RX_BUFFER (AWS_IOT_MQTT_RX_BUF_LEN + 1)
#endif

#define MAX_SIZE_OF_UNIQUE_CLIENT_ID_BYTES 80
#define MAX_SIZE_CLIENT_ID_WITH_SEQUENCE (MAX_SIZE_OF_UNIQUE_CLIENT_ID_BYTES + 10)
#define MAX_SIZE_CLIENT_TOKEN_CLIENT_SEQUENCE (MAX_SIZE_CLIENT_ID_WITH_SEQUENCE + 20)
#define MAX_ACKS_TO_COMEIN_AT_ANY_GIVEN_TIME CONFIG_AWS_IOT_SHADOW_MAX_SIMULTANEOUS_ACKS
#define MAX_THINGNAME_HANDLED_AT_ANY_GIVEN_TIME CONFIG_AWS_IOT_SHADOW_MAX_SIMULTANEOUS_THINGNAMES
#define MAX_JSON_TOKEN_EXPECTED CONFIG_AWS_IOT_SHADOW_MAX_JSON_TOKEN_EXPECTED
#define MAX_SHADOW_TOPIC_LENGTH_WITHOUT_THINGNAME CONFIG_AWS_IOT_SHADOW_MAX_SHADOW_TOPIC_LENGTH_WITHOUT_THINGNAME
#define MAX_SIZE_OF_THING_NAME CONFIG_AWS_IOT_SHADOW_MAX_SIZE_OF_THING_NAME
#define MAX_SHADOW_TOPIC_LENGTH_BYTES (MAX_SHADOW_TOPIC_LENGTH_WITHOUT_THINGNAME + MAX_SIZE_OF_THING_NAME)

// Auto Reconnect settings
#define AWS_IOT_MQTT_MIN_RECONNECT_WAIT_INTERVAL CONFIG_AWS_IOT_MQTT_MIN_RECONNECT_WAIT_INTERVAL
#define AWS_IOT_MQTT_MAX_RECONNECT_WAIT_INTERVAL CONFIG_AWS_IOT_MQTT_MAX_RECONNECT_WAIT_INTERVAL

// TLS settings
#define IOT_SSL_READ_TIMEOUT_MS 3
#define IOT_SSL_READ_RETRY_TIMEOUT_MS 10
#define IOT_SSL_WRITE_RETRY_TIMEOUT_MS 10

#endif /* _AWS_IOT_CONFIG_H_ */
